=== oowekyala/pmd/pmd-test-schema/src/main/resources/net/sourceforge/pmd/test/schema/rule-tests_1_2_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Version 1.1.1 -->
<!-- Last change: 2025-08-08 -->
<!-- Changes against 1.1.0: allow empty expected-suppression (without suppressor children) -->
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:tns="http://pmd.sourceforge.net/rule-tests"
        targetNamespace="http://pmd.sourceforge.net/rule-tests"
        elementFormDefault="qualified">

    <element name="test-data">
        <complexType>
            <choice maxOccurs="unbounded">
                <element name="test-code" minOccurs="0" maxOccurs="unbounded" type="tns:testType"/>
                <element name="code-fragment" minOccurs="0" maxOccurs="unbounded" type="tns:codeFragmentType">
                    <annotation>
                        <documentation>
                            A code fragment that can be referred to by several tests.
                        </documentation>
                    </annotation>
                </element>
            </choice>
        </complexType>
    </element>

    <complexType name="testType">
        <sequence>
            <element name="description" type="string"/>
            <element name="rule-property" minOccurs="0" maxOccurs="unbounded">
                <complexType>
                    <simpleContent>
                        <extension base="string">
                            <attribute name="name" type="string" use="required"/>
                        </extension>
                    </simpleContent>
                </complexType>
            </element>

            <choice>
                <element name="annotated-code">
                    <annotation>
                        <documentation>
                            Source fragment annotated with comments to tag the expected violations and suppressions.
                        </documentation>
                    </annotation>
                    <complexType>
                        <simpleContent>
                            <extension base="string">
                                <attribute name="language-version" type="string"/>
                            </extension>
                        </simpleContent>
                    </complexType>
                </element>
                <sequence>
                    <element name="expected-problems" type="nonNegativeInteger"/>
                    <element name="expected-linenumbers" type="string" minOccurs="0"/>
                    <element name="expected-messages" minOccurs="0">
                        <complexType>
                            <sequence>
                                <element name="message" type="string" maxOccurs="unbounded"/>
                            </sequence>
                        </complexType>
                    </element>
                    <element name="expected-suppressions" minOccurs="0">
                        <annotation>
                            <documentation>Declares the expected suppressed violations. Since PMD 7.15.0 / rule-tests
                                1.1.0.
                            </documentation>
                        </annotation>
                        <complexType>
                            <sequence>
                                <element name="suppressor" minOccurs="0" maxOccurs="unbounded">
                                    <complexType>
                                        <simpleContent>
                                            <extension base="string">
                                                <attribute name="line" type="positiveInteger" use="required"/>
                                            </extension>
                                        </simpleContent>
                                    </complexType>
                                </element>
                            </sequence>
                        </complexType>
                    </element>
                    <choice>
                        <element name="code" type="string"/>
                        <element name="code-ref">
                            <complexType>
                                <attribute name="id" type="IDREF" use="required"/>
                            </complexType>
                        </element>
                    </choice>
                    <element name="source-type" minOccurs="0" default="" type="string">
                        <annotation>
                            <documentation>
                                Language version of the source, eg 'java 8'.
                            </documentation>
                        </annotation>
                    </element>
                </sequence>
            </choice>
        </sequence>
        <attribute name="reinitializeRule" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="regressionTest" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated. Use "disabled" instead.
                    If this attribute is set to "false", then the test is ignored.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="useAuxClasspath" type="boolean" default="true">
            <annotation>
                <documentation>
                    This attribute is deprecated, it is assumed true and ignored.
                </documentation>
            </annotation>
        </attribute>

        <attribute name="disabled" type="boolean" default="false">
            <annotation>
                <documentation>
                    A reason why the test is disabled/ignored should be provided as a comment for the test.
                </documentation>
            </annotation>
        </attribute>
        <attribute name="focused" type="boolean" default="false">
            <annotation>
                <documentation>
                    If true, only this test will be executed, and all others will be disabled.
                    If several tests in the same file are focused, then the last one wins, in
                    document order.
                    This attribute is provided as a way for developers to temporarily focus on a single test.
                    Test files with a focused test should not be checked in. For this reason,
                    using this attribute produces a warning.
                </documentation>
            </annotation>
        </attribute>
    </complexType>

    <complexType name="codeFragmentType">
        <simpleContent>
            <extension base="string">
                <attribute name="id" type="ID" use="required"/>
            </extension>
        </simpleContent>
    </complexType>
</schema>

=== oowekyala/pmd/pmd-test-schema/src/test/resources/net/sourceforge/pmd/test/schema/AnnotatedCodeTests.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ BSD-style license; for more info see http://pmd.sourceforge.net/license.html
  -->

<test-data
        xmlns="http://pmd.sourceforge.net/rule-tests"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests https://pmd.github.io/schema/rule-tests_1_2_0.xsd">

    <test-code>
        <description>No violations</description>
        <annotated-code><![CDATA[
            class Test {
                public record NestedRecord(int x, int y) { }
                // unrelated comment
            }
        ]]></annotated-code>
    </test-code>


    <!-- Old style test -->
    <test-code>
        <description>Old style test</description>
        <expected-problems>1</expected-problems>
        <expected-linenumbers>3-3</expected-linenumbers>
        <expected-messages>
            <message>The initializer for variable 'i' is never used (overwritten on line 4)</message>
        </expected-messages>
        <code><![CDATA[
            public class Foo {
                void bar() {
                    int i=0;
                    i=1;
                    if (i==2) {}
                }
            }
            ]]></code>
    </test-code>

    <test-code>
        <description>New style test</description>
        <annotated-code><![CDATA[
            public class Foo {
                void bar() {
                    int i=0; // warn: The initializer for variable 'i' is never used (overwritten on line 4)
                    i=1;
                    if (i==2) {}
                }
            }
        ]]></annotated-code>
    </test-code>

    <test-code>
        <description>No message</description>
        <annotated-code><![CDATA[
            public class Foo {
                void bar() {
                    int i=0; // warn
                }
            }
            ]]>
        </annotated-code>
    </test-code>

    <test-code>
        <description>Multiple violations</description>
        <annotated-code><![CDATA[
            public class Foo {
                void bar(int i) {
                    int j = 0; // warn: The initializer for variable 'j' is never used (overwritten on lines 6 and 9)
                    int z = 0;
                    if (i < 10) {
                        j = i; // warn(+1): The value assigned to variable 'j' is never used
                        throw new Exception();
                    } else {
                        j = z;
                    }
                    System.out.println(j);
                }
            }
        ]]></annotated-code>
    </test-code>

    <test-code>
        <description>Suppressed violations</description>
        <annotated-code><![CDATA[
            public class Foo {
                @SuppressWarnings("PMD")
                void bar(int i) {
                    int j = 0; // suppressed(@SuppressWarnings)(+2): The initializer for variable 'j' is never used (overwritten on lines 6 and 9)
                    int z = 0;
                    if (i < 10) {
                        j = i;
                        throw new Exception();
                    } else {
                        j = z;
                    }
                    System.out.println(j);
                }
            }
            ]]></annotated-code>
    </test-code>

    <test-code>
        <description>Multiple violations on same line</description>
        <annotated-code><![CDATA[
            public class Foo {
                @SuppressWarnings("PMD")
                void bar(int i) {
                    //+2 warn: something
                    //+1 warn: something else
                    int j = 0; // suppressed(@SuppressWarnings)(+2): a suppression
                    int z = 0;
                    if (i < 10) {
                        j = i;
                        throw new Exception();
                    } else {
                        j = z;
                    }
                    System.out.println(j);
                }
            }
            ]]></annotated-code>
    </test-code>



</test-data>
